### PR TITLE
Fixes for several open issues

### PR DESCRIPTION
**Pull request by patcon**
I started try to cherry pick each of these out of my working branch, but then realized they were pretty tightly coupled. They all seem pretty atomic if you view them by commit, and I was hoping you could review each commit in this master PR instead :)

This PR resolves: #52, #53, #55, #56, #57

### CODE REVIEW

**Comment by patcon** [comment]
Hm. One sec. Hitting on tiny edge-case for the standalone cento-6 suites, related to this:
https://jira.atlassian.com/browse/JRA-31444

I think I can fix it

**Comment by patcon** [comment]
I've got some other PRs to submit, but given that they depend on a working test suite, and it's broken for me without some of the commits in here, I'll consider my self blocked.

Please let me know if there's anything at all that I can do to expedite review (such as separating out any commits that you're less sure you want to merge). Thanks @mvdkleijn!

**Comment by mvdkleijn** [comment]
I don't really consider these tightly coupled personally and in general don't like combination PRs. I'll take a look though.

**Comment by patcon** [comment]
Thanks! Duly noted for next time. By "tightly coupled". I meant that cherry-picking each commit was very messy for some reason, and I was hoping not to have to tease apart my development branch in PRs :)

**Pull request merged**
