### PR TITLE
Allow to override apache webapp configuration in a wrapper cookbook

### PR DESCRIPTION
**Pull request by obazoud**

### CODE REVIEW

**Comment by legal90** [comment]
+1 on this. I think, it should be ported to `confluence` and `stash` cookbooks as well.

**Comment by legal90** [comment]
But an attribute name (`default['jira']['apache2']['cookbook']`) looks a little bit confusing. Without a context it's not clear what exactly this attribute means. Looks confusing - "Is it a cookbook for apache2?"

May be, it's better to call it `default['jira']['apache2']['template_cookbook']` or something like that?

**Comment by obazoud** [comment]
ok for `template_cookbook`.
`confluence` should be my next step.

**Comment by mvdkleijn** [comment]
First of all, happy 2016! :smile: 

Secondly, maybe I'm missing something but we already override the Apache web app config template in a wrapper cookbook ourselves using rewind... so I'm unsure why this is needed?

**Comment by obazoud** [comment]
Yes of course I can use rewind but it's better to have this feature out of the box.

**Comment by mvdkleijn** [comment]
Right! I should've looked a little deeper. I wasn't familiar with the cookbook parameter in the template directive, hence my initial confusion.

Change accepted of course. :+1:

**Comment by obazoud** [comment]
Thanks!

**Pull request merged**
