### PR TITLE
Https validation

### PR DESCRIPTION
**Pull request by itjuan**
Hello, as promised on the ticket i opened: https://github.com/afklm/jira/issues/78#issuecomment-240210303

This commit is for fixing and making validation with the next attribues:
**node['jira']['apache2']['ssl']['enable']**
- If you want to enable SSL on your site. Default true.

**node['jira']['apache2']['ext_proxy']['enabled']**
- If you want to use an external proxy. Default false.

Please let me know in case of any question or comment.

Hope it helps :)

### CODE REVIEW

**Comment by mrjcleaver** [comment]
Thanks for the code, appreciated!
But, hmm. Looks like it failed a test.

**Comment by itjuan** [comment]
No problem Sir. Let me take a look at this ASAP.

Regards.

**Comment by mvdkleijn** [comment]
Sorry guys, that's my issue. I wanted to run tests against a DO instance but am having issues with kitchen not doing what I want. :wink:

**Comment by itjuan** [comment]
I'm not able to reproduce the problem with the PR on my local env :/

**Comment by legal90** [comment]
Thanks for contribution! But I have some notices about this PR. 
As I can see, it might be solving the problem for the case with external reverse proxy (which is not supported yet, by the way). But it could also introduce some issues with the general use case:

1) Just about the UX: New attributes have different semantics: _enable_ vs _enable**d**_. I'd recommend using "enabled" because such form is already used in other attributes.

2) If both of new attributes are `true`, then there will be duplicated entries for  _proxyName_ and _proxyPort_ in `server.xml`.

3) Currently, TLS/SSL is not optional in this cookbook. In the general use case the local proxy is configured to work with TLS/SSL: https://github.com/afklm/jira/blob/316d80be01a333d1165f37565275a2ee94e92fbd/templates/default/web_app.conf.erb
If you want to make it optional, then patching `server.xml` is not enough and local Apache configuration should be also changed. But it's better to do it in a separate PR.

**Comment by mvdkleijn** [comment]
Closing this PR in favour of another approach similar to the Confluence cookbook.

**Pull request closed without merging**
