### PR TITLE
Added Jira 7.0.0 compatibility.

### PR DESCRIPTION
**Pull request by patcon**
Supersedes #12

### CODE REVIEW

**Comment by ramonskie** [comment]
we also need to add the 2 different jira types
- jira software
- jira core
because the agile part is not a plugin anymore

**Comment by mvdkleijn** [comment]
I already have some thoughts on how I want to add the different products. I'll work on that this week.

**Comment by patcon** [comment]
Sounds good. From a quick look around, it seems that the only difference is where the tarball is downloaded from, as all the other setup is the same, in case you still felt like merging this and building from there (regardless, we'll need to handle varying server.xml files)

**Comment by mvdkleijn** [comment]
Closing this in favor of #41

**Pull request closed without merging**
